services:
  backend:
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    depends_on:
      - db
      - minio
    command: [ "npm", "run", "dev" ]
    networks:
      - uniblog_net

  db:
    image: postgres:17
    container_name: DataBasePostgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uniblog
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - uniblog_net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    container_name: minio_DataStorage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: userPassword
      MINIO_ROOT_PASSWORD: userPassword
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - uniblog_net

volumes:
  db-data:
  minio-data:


networks:
  uniblog_net:
